# Generated by Django 4.0.5 on 2023-01-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPUserConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=100)),
                ('e_mail_conf', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('password_conf', models.CharField(max_length=50)),
            ],
        ),
    ]
