# Generated by Django 4.0.5 on 2023-02-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPUserConf',
        ),
    ]
