# Generated by Django 4.0.5 on 2022-12-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_category_tag_recentposts_expandpost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expandpost',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='postblog',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recentposts',
            old_name='title',
            new_name='name',
        ),
    ]
