# Generated by Django 4.0.5 on 2022-12-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_expandpost_image_postblog_slug_alter_postblog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='textblog',
            field=models.TextField(blank=True),
        ),
    ]
