# Generated by Django 4.0.5 on 2022-12-28 09:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_postblog_textblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expandpost',
            name='textblog',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
