# Generated by Django 4.0.5 on 2023-01-09 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0009_alter_expandpost_textblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postblog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
            preserve_default=False,
        ),
    ]
