# Generated by Django 4.0.5 on 2023-01-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_expandpost_user_postblog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblog',
            name='textblog',
        ),
    ]
