# Generated by Django 4.0.5 on 2023-01-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_remove_postblog_textblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expandpost',
            name='url',
        ),
        migrations.RemoveField(
            model_name='postblog',
            name='url',
        ),
    ]
