# Generated by Django 4.0.5 on 2023-01-10 05:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_expandpost_url_remove_postblog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='textblog',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
