# Generated by Django 4.0.5 on 2023-01-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_postblog_textblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblog',
            name='textblog',
        ),
    ]
