# Generated by Django 4.0.5 on 2023-01-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_remove_postblog_textblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expandpost',
            name='category',
        ),
    ]
