# Generated by Django 4.0.5 on 2023-01-20 06:53

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_expandpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expandpost',
            name='textblog',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
