# Generated by Django 4.0.5 on 2023-02-01 06:50

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_expandpost_textblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expandpost',
            name='textblog',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
