# Generated by Django 4.0.5 on 2023-02-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_expandpost_textblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandpost',
            name='textblog_default',
            field=models.TextField(default=''),
        ),
    ]
