# Generated by Django 4.0.5 on 2023-02-01 07:40

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_expandpost_textblog_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_editorjs_custom', django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='expandpost',
            name='textblog_default',
        ),
        migrations.AlterField(
            model_name='expandpost',
            name='textblog',
            field=models.TextField(default=''),
        ),
    ]
