# Generated by Django 4.0.5 on 2023-02-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_comment_posttext_delete_post_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttext',
            name='body_custom',
        ),
        migrations.RemoveField(
            model_name='posttext',
            name='body_default',
        ),
        migrations.RemoveField(
            model_name='posttext',
            name='body_textfield',
        ),
    ]
