# Generated by Django 4.0.5 on 2023-02-01 10:11

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_posttext_body_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expandpost',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(default=''),
        ),
    ]
