# Generated by Django 4.0.5 on 2023-02-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_expandpost_body_editorjs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expandpost',
            unique_together={('name', 'postblog', 'body_editorjs')},
        ),
    ]
