# Generated by Django 4.0.5 on 2023-02-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_expandpost_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expandpost',
            name='image',
        ),
    ]
