# Generated by Django 4.0.5 on 2023-02-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_expandpost_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expandpost',
            unique_together=set(),
        ),
    ]
